# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/matthew/Matthew/UCT/2020/Embedded3/Image-Masking-Accelerator/ima_com_connection/ima_com_connection.cache/wt [current_project]
set_property parent.project_path /home/matthew/Matthew/UCT/2020/Embedded3/Image-Masking-Accelerator/ima_com_connection/ima_com_connection.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys-a7-100t:part0:1.0 [current_project]
set_property ip_output_repo /home/matthew/Matthew/UCT/2020/Embedded3/Image-Masking-Accelerator/ima_com_connection/ima_com_connection.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files /home/matthew/Matthew/UCT/2020/Embedded3/Image-Masking-Accelerator/ima_com_connection/ima_com_connection.srcs/sources_1/imports/init_files/blue.coe
add_files /home/matthew/Matthew/UCT/2020/Embedded3/Image-Masking-Accelerator/ima_com_connection/ima_com_connection.srcs/sources_1/imports/init_files/horse.coe
add_files /home/matthew/Matthew/UCT/2020/Embedded3/Image-Masking-Accelerator/ima_com_connection/ima_com_connection.srcs/sources_1/imports/init_files/red.coe
read_verilog -library xil_defaultlib {
  /home/matthew/Matthew/UCT/2020/Embedded3/Image-Masking-Accelerator/ima_com_connection/ima_com_connection.srcs/sources_1/new/Debounce.v
  /home/matthew/Matthew/UCT/2020/Embedded3/Image-Masking-Accelerator/ima_com_connection/ima_com_connection.srcs/sources_1/new/uart_rx.v
  /home/matthew/Matthew/UCT/2020/Embedded3/Image-Masking-Accelerator/ima_com_connection/ima_com_connection.srcs/sources_1/imports/new/vga.v
  /home/matthew/Matthew/UCT/2020/Embedded3/Image-Masking-Accelerator/ima_com_connection/ima_com_connection.srcs/sources_1/new/imu_controller.v
}
read_ip -quiet /home/matthew/Matthew/UCT/2020/Embedded3/Image-Masking-Accelerator/ima_com_connection/ima_com_connection.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci
set_property used_in_implementation false [get_files -all /home/matthew/Matthew/UCT/2020/Embedded3/Image-Masking-Accelerator/ima_com_connection/ima_com_connection.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc]
set_property is_locked true [get_files /home/matthew/Matthew/UCT/2020/Embedded3/Image-Masking-Accelerator/ima_com_connection/ima_com_connection.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci]

read_ip -quiet /home/matthew/Matthew/UCT/2020/Embedded3/Image-Masking-Accelerator/ima_com_connection/ima_com_connection.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all /home/matthew/Matthew/UCT/2020/Embedded3/Image-Masking-Accelerator/ima_com_connection/ima_com_connection.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]
set_property is_locked true [get_files /home/matthew/Matthew/UCT/2020/Embedded3/Image-Masking-Accelerator/ima_com_connection/ima_com_connection.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci]

read_ip -quiet /home/matthew/Matthew/UCT/2020/Embedded3/Image-Masking-Accelerator/ima_com_connection/ima_com_connection.srcs/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3.xci
set_property used_in_implementation false [get_files -all /home/matthew/Matthew/UCT/2020/Embedded3/Image-Masking-Accelerator/ima_com_connection/ima_com_connection.srcs/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3_ooc.xdc]
set_property is_locked true [get_files /home/matthew/Matthew/UCT/2020/Embedded3/Image-Masking-Accelerator/ima_com_connection/ima_com_connection.srcs/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3.xci]

read_ip -quiet /home/matthew/Matthew/UCT/2020/Embedded3/Image-Masking-Accelerator/ima_com_connection/ima_com_connection.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2.xci
set_property used_in_implementation false [get_files -all /home/matthew/Matthew/UCT/2020/Embedded3/Image-Masking-Accelerator/ima_com_connection/ima_com_connection.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2_ooc.xdc]
set_property is_locked true [get_files /home/matthew/Matthew/UCT/2020/Embedded3/Image-Masking-Accelerator/ima_com_connection/ima_com_connection.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/matthew/Matthew/UCT/2020/Embedded3/Image-Masking-Accelerator/ima_com_connection/ima_com_connection.srcs/constrs_1/new/Constraints.xdc
set_property used_in_implementation false [get_files /home/matthew/Matthew/UCT/2020/Embedded3/Image-Masking-Accelerator/ima_com_connection/ima_com_connection.srcs/constrs_1/new/Constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top imu_controller -part xc7a100tcsg324-1


write_checkpoint -force -noxdef imu_controller.dcp

catch { report_utilization -file imu_controller_utilization_synth.rpt -pb imu_controller_utilization_synth.pb }
